### ISSUE TITLE
receives in the plugin patch are not parsed correctly if too many dashes are in the receive object box.

### ISSUE THREAD

**Issue by unknownError** [x37v/pdlv2#2]
in plugins/demo_sine_synth/plugin.pd parameters for vibrato frequency and depth are not responding when changed in the host.

this does not work: r $1-lv2-vib-freq

removing the dash it works: r $1-lv2-vibFreq

**Comment by x37v** [comment]
I believe this is fixed in d7a811e807e53ebfd2ef80757ba4c4b58fb61fa3

I'm mapping whatever happens after lv2- directly to the lv2 symbol which means that it has to be a valid c identifier, no dashes allowed. I added a format check in the processing script and fixed up the sine plugin. Maybe in the future I can allow for more varieties of names but _vib_freq_ or _vibFreq_ for now should work, just not _vib-freq_.

Good catch btw, @unknownError, looking into that also exposed an issue with my pd file line continuation removal.
